---
RR-1:
  hostname: 10.0.0.231
  groups:
    - cisco_group
  data:
    hostname: RR-1
    ospf:
      ospf_rid: 11.11.11.11
      ospf_process: "1"
      ospf_networks:
        - ip: 10.111.0.0
          wildcard: 0.0.0.3
          area: "0"
        - ip: 10.112.0.0
          wildcard: 0.0.0.3
          area: "0"
        - ip: 10.113.0.0
          wildcard: 0.0.0.3
          area: "0"
        - ip: 10.114.0.0
          wildcard: 0.0.0.3
          area: "0"
    interfaces:
      - name: loopback 0
        description: loopback interface
        ip: 11.11.11.11
        mask: 255.255.255.255
        enabled: true
      - name: GigabitEthernet0/1
        description: LAN
        ip: 10.111.0.1
        mask: 255.255.255.252
        enabled: true
      - name: GigabitEthernet0/2
        description: LAN
        ip: 10.112.0.1
        mask: 255.255.255.252
        enabled: true
      - name: GigabitEthernet0/3
        description: LAN
        ip: 10.113.0.1
        mask: 255.255.255.252
        enabled: true
      - name: GigabitEthernet0/4
        description: LAN
        ip: 10.114.0.1
        mask: 255.255.255.252
        enabled: true
RR-2:
  hostname: 10.0.0.232
  groups:
    - cisco_group
  data:
    hostname: RR-2
    ospf:
      ospf_rid: 22.22.22.22
      ospf_process: "1"
      ospf_networks:
        - ip: 10.121.0.0
          wildcard: 0.0.0.3
          area: "0"
        - ip: 10.122.0.0
          wildcard: 0.0.0.3
          area: "0"
        - ip: 10.123.0.0
          wildcard: 0.0.0.3
          area: "0"
        - ip: 10.124.0.0
          wildcard: 0.0.0.3
          area: "0"
    interfaces:
      - name: loopback 0
        description: loopback interface
        ip: 22.22.22.22
        mask: 255.255.255.255
        enabled: true
      - name: GigabitEthernet0/1
        description: LAN
        ip: 10.121.0.1
        mask: 255.255.255.252
        enabled: true
      - name: GigabitEthernet0/2
        description: LAN
        ip: 10.122.0.1
        mask: 255.255.255.252
        enabled: true
      - name: GigabitEthernet0/3
        description: LAN
        ip: 10.123.0.1
        mask: 255.255.255.252
        enabled: true
      - name: GigabitEthernet0/3
        description: LAN
        ip: 10.123.0.1
        mask: 255.255.255.252
        enabled: true
      - name: GigabitEthernet0/4
        description: LAN
        ip: 10.124.0.1
        mask: 255.255.255.252
        enabled: true
R1:
  hostname: 10.0.0.233
  groups:
    - cisco_group
  data:
    hostname: R1
    ospf:
      ospf_rid: 1.1.1.1
      ospf_process: "1"
      ospf_networks:
        - ip: 10.111.0.0
          wildcard: 0.0.0.3
          area: "0"
        - ip: 10.112.0.0
          wildcard: 0.0.0.3
          area: "0"
    interfaces:
      - name: loopback 0
        description: loopback interface
        ip: 1.1.1.1
        mask: 255.255.255.255
        enabled: true
      - name: GigabitEthernet0/1
        description: LAN
        ip: 10.111.0.2
        mask: 255.255.255.252
        enabled: true
      - name: GigabitEthernet0/2
        description: LAN
        ip: 10.112.0.2
        mask: 255.255.255.252
        enabled: true
R2:
  hostname: 10.0.0.234
  groups:
    - cisco_group
  data:
    hostname: R2
    ospf:
      ospf_rid: 2.2.2.2
      ospf_process: "1"
      ospf_networks:
        - ip: 10.112.0.0
          wildcard: 0.0.0.3
          area: "0"
        - ip: 10.122.0.0
          wildcard: 0.0.0.3
          area: "0"
    interfaces:
      - name: loopback 0
        description: loopback interface
        ip: 2.2.2.2
        mask: 255.255.255.255
        enabled: true
      - name: GigabitEthernet0/1
        description: LAN
        ip: 10.112.0.2
        mask: 255.255.255.252
        enabled: true
      - name: GigabitEthernet0/2
        description: LAN
        ip: 10.122.0.2
        mask: 255.255.255.252
        enabled: true
R3:
  hostname: 10.0.0.235
  platform: "ios"
  username: vish
  password: cisco
  groups:
    - cisco_group
  data:
    hostname: R3
    ospf:
      ospf_rid: 3.3.3.3
      ospf_process: "1"
      ospf_networks:
        - ip: 10.113.0.0
          wildcard: 0.0.0.3
          area: "0"
        - ip: 10.123.0.0
          wildcard: 0.0.0.3
          area: "0"
    interfaces:
      - name: loopback 0
        description: loopback interface
        ip: 3.3.3.3
        mask: 255.255.255.255
        enabled: true
      - name: GigabitEthernet0/1
        description: LAN
        ip: 10.113.0.2
        mask: 255.255.255.252
        enabled: true
      - name: GigabitEthernet0/2
        description: LAN
        ip: 10.123.0.2
        mask: 255.255.255.252
        enabled: true
R4:
  hostname: 10.0.0.236
  platform: "ios"
  username: vish
  password: cisco
  groups:
    - cisco_group
  data:
    hostname: R4
    ospf:
      ospf_rid: 4.4.4.4
      ospf_process: "1"
      ospf_networks:
        - ip: 10.114.0.0
          wildcard: 0.0.0.3
          area: "0"
        - ip: 10.124.0.0
          wildcard: 0.0.0.3
          area: "0"
    interfaces:
      - name: loopback 0
        description: loopback interface
        ip: 4.4.4.4
        mask: 255.255.255.255
        enabled: true
      - name: GigabitEthernet0/1
        description: LAN
        ip: 10.114.0.2
        mask: 255.255.255.252
        enabled: true
      - name: GigabitEthernet0/2
        description: LAN
        ip: 10.124.0.2
        mask: 255.255.255.252
        enabled: true
